export const brainrotNames = [
  "Skibidi Toilet",
  "Baby Gronk",
  "Livvy Dunne",
  "Kai Cenat",
  "Fanum Taxer",
  "Sigma Male",
  "Hawk Tuah",
  "Grimace Shake",
  "Mewing King",
  "Looksmaxxer",
  "Gyatt Detector",
  "Ohio Resident",
  "Subway Surfer",
  "Adin Ross",
  "Chat Is This Real",
  "Glazing Expert",
  "W Rizzler",
  "Ice Spice",
  "Duke Dennis",
  "Gooner Prime",
  "Skibidi Sigma",
  "Fanum Tax Evader",
  "GigaChad",
  "Bussin Bussin",
  "No Cap",
  "Fr Fr"
];
